# Generated by Django 4.0 on 2023-06-21 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport_event_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportevent',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='sportevent',
            name='location',
        ),
    ]
