# Generated by Django 4.0 on 2023-06-22 06:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sport_event_app', '0002_remove_sportevent_coach_remove_sportevent_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportevent',
            name='date',
        ),
        migrations.AddField(
            model_name='sportevent',
            name='event_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
