# Generated by Django 4.0 on 2023-06-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_event_app', '0003_remove_sportevent_date_sportevent_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportevent',
            name='announce_text',
            field=models.TextField(default='', max_length=280),
        ),
        migrations.AlterField(
            model_name='sportevent',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
