# Generated by Django 4.0 on 2023-06-25 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport_event_app', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='description',
            field=models.TextField(default='', max_length=280),
        ),
        migrations.AddField(
            model_name='coach',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='coach',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sport_event_app.profile'),
        ),
        migrations.AddField(
            model_name='coach',
            name='specialization',
            field=models.CharField(default='Тренер', max_length=140),
        ),
        migrations.AddField(
            model_name='location',
            name='default_coach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sport_event_app.coach'),
        ),
        migrations.AddField(
            model_name='location',
            name='default_duration',
            field=models.DurationField(default='01:00:00'),
        ),
        migrations.AddField(
            model_name='location',
            name='default_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='default_seats_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='location_address',
            field=models.TextField(default='', max_length=280),
        ),
        migrations.AddField(
            model_name='location',
            name='max_seats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='sportevent',
            name='coach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sport_event_app.coach'),
        ),
        migrations.AddField(
            model_name='sportevent',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sport_event_app.location'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='middle_name',
            field=models.TextField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.TextField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='surname',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats_count', models.PositiveIntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport_event_app.sportevent')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport_event_app.profile')),
            ],
        ),
    ]
