# Generated by Django 4.0 on 2023-06-26 18:20

from django.db import migrations, models
import sport_event_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_event_app', '0006_coach_description_coach_image_coach_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[(sport_event_app.models.ReservationStatusChoice['APPROVED'], 'Approved'), (sport_event_app.models.ReservationStatusChoice['NOTIFIED'], 'Notified'), (sport_event_app.models.ReservationStatusChoice['REGISTERED'], 'Registered')], max_length=100, null=True),
        ),
    ]
