# Generated by Django 4.0 on 2023-06-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_event_app', '0007_reservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('APP', 'Approved'), ('NFY', 'Notified'), ('REG', 'Registered')], default='REG', max_length=4, null=True),
        ),
    ]
