# Generated by Django 4.0 on 2023-06-28 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_event_app', '0008_alter_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='coach',
            name='image',
            field=models.ImageField(default='media/coach_default.png', null=True, upload_to=''),
        ),
    ]
