# Generated by Django 4.0 on 2023-06-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_event_app', '0009_location_image_alter_coach_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.TextField(default='', max_length=500),
        ),
    ]
